# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache: bundler
services:
  - postgresql
  - mysql
rvm:
  - 2.5.0
  - ruby-head
env:
  - DB=pg
  - DB=sqlite3
  - DB=mysql
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile
before_script:
  - psql -c 'create database activerecord_like_test' -U postgres
  - mysql -e 'create database activerecord_like_test'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
