# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache: bundler
services:
  - postgresql
  - mysql
rvm:
  - 2.7.5
  - 3.0.3
  - ruby-head
env:
  - DB=pg
  - DB=sqlite3
  - DB=mysql
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
