language: ruby
cache: bundler
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
env:
  - DB=pg
  - DB=sqlite3
  - DB=mysql
before_script:
  - psql -c 'create database activerecord_like_test' -U postgres
  - mysql -e 'create database activerecord_like_test'
